In [24]:
import os
import pickle
import pandas as pd
import numpy as np
from sklearn import linear_model
import joblib

In [3]:
# Set path to csv
homeprices_path = os.path.join("2_linear_regression", "homeprices.csv")
df = pd.read_csv(homeprices_path)
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [4]:
model = linear_model.LinearRegression()
model.fit(df[['area']], df.price)

LinearRegression()

In [5]:
model.coef_

array([135.78767123])

In [6]:
model.intercept_

180616.43835616432

In [9]:
model.predict([[5000]])

array([859554.79452055])

In [20]:
# Enter x
x = 5000

# Find y_predicted
y_predicted = model.coef_ * x + model.intercept_

# Print results
print(f"${round(float(y_predicted[0]),2)}")

$859554.79


In [14]:
with open('model_pickle', 'wb') as f:
    pickle.dump(model, f)

In [16]:
with open('model_pickle', 'rb') as f:
    mp = pickle.load(f)

In [18]:
mp.predict([[5000]])

array([859554.79452055])

In [25]:
joblib.dump(model, 'model_joblib')

['model_joblib']

In [26]:
mj = joblib.load('model_joblib')

In [27]:
mj.predict([[5000]])

array([859554.79452055])